spring.application.name=ms-upload-video
email.service.url=http://localhost:2323

# ===============================
#  Configuração do Banco
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/db_upload_video

# ===============================
server.port=${PORTA:1030}
# ====================================

# = Configurações do Spring security =
# ====================================
spring.security.user.name=dev
spring.security.user.password=735ac83f-4ce5-4880-969c-a5a9d4039ac1

# ====================================
# = Configurações do Spring rabbitmq =
# ====================================
#spring.rabbitmq.addresses=amqps://dwfxmakn:nTAUwGizmhqKNYjHwdpforivCXlMbZPV@jaragua.lmq.cloudamqp.com/dwfxmakn
#broker.queue.email.name=default.email

# ======================================
# Configurações Spring mail
# ======================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.password=sdcf ebtq davs zdkx
spring.mail.username=gresslerapi@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ======================================
# Configurações Logging Level
# ======================================
logging.level.root=INFO
logging.level.com.dev.api_agenda=DEBUG
logging.file.name=logs/videos.log
